In [1]:
# method to get the iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
# feature names of iris dataset
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
# categorical target values
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
# take the first two features to use for classification
X_train = iris.data[:, :2]
X_train[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [23]:
# take the categorical class/target values
Y_train = (iris['target'] == 0) * 1
Y_train[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
# define function to calculate sigmoid of a vector 
import numpy as np
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [22]:
# loss function to calculate cost for all of the predictions 
def loss(y, h):
    return (-y * np.log(h) - (1-y)*np.log(1-h)).mean()

In [28]:
# stitching the algorithm 
def fit(X, y, num_iter = 10000, learning_rate = 0.01):
    # initialize theta values with zeroes
    theta = np.zeros(X_train.shape[1])
    
    for i in range(num_iter):
        z = np.dot(X, theta)
        h = sigmoid(z)
        # get the gradient vector of loss function
        gradient = np.dot(X.T, (h-y)) / y.size
        
        #update the theta vector
        theta -=  learning_rate * gradient
    
    return theta


In [25]:
# define function to get the prediction probability
def predict_prob(X, theta):
    return sigmoid(np.dot(X, theta))

In [26]:
# define function to get the prediction values
def predict(X, theta, threshold = 0.5):
    return predict_prob(X, theta) >= threshold

In [30]:
# fitting the model
theta = fit(X_train, Y_train)
theta

array([-2.87860762,  4.9396812 ])

In [31]:
#predict the target values
preds = predict(X_train, theta)
preds

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [34]:
accuracy = ((np.sum( (preds*1) == Y_train )/Y_train.shape[0])*100)
accuracy

99.33333333333333